name: healthcare-9to9-et
on:
  schedule:
    - cron: '0 13 * * *'   # 09:00 ET resume (EDT=UTC-4)
    - cron: '0 1 * * *'    # 21:00 ET suspend (EDT=UTC-4)
  workflow_dispatch:

jobs:
  resume:
    if: github.event.schedule == '0 13 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Resume service
        run: |
          curl -sf -X POST \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_HEALTHCARE }}/resume" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}"
  suspend:
    if: github.event.schedule == '0 1 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Suspend service
        run: |
          curl -sf -X POST \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_HEALTHCARE }}/suspend" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}"
